// Autogenerated from Pigeon (v4.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class ObsRequest;
@class ObsResponse;

@interface ObsRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFilePath:(NSString *)filePath
    accessKey:(NSString *)accessKey
    secretKey:(NSString *)secretKey
    endpoint:(NSString *)endpoint
    bucket:(NSString *)bucket
    securityToken:(NSString *)securityToken
    prefix:(nullable NSString *)prefix
    fileName:(nullable NSString *)fileName;
@property(nonatomic, copy) NSString * filePath;
@property(nonatomic, copy) NSString * accessKey;
@property(nonatomic, copy) NSString * secretKey;
@property(nonatomic, copy) NSString * endpoint;
@property(nonatomic, copy) NSString * bucket;
@property(nonatomic, copy) NSString * securityToken;
@property(nonatomic, copy, nullable) NSString * prefix;
@property(nonatomic, copy, nullable) NSString * fileName;
@end

@interface ObsResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithObjectUrl:(NSString *)objectUrl;
@property(nonatomic, copy) NSString * objectUrl;
@end

/// The codec used by ObsClientAPI.
NSObject<FlutterMessageCodec> *ObsClientAPIGetCodec(void);

@protocol ObsClientAPI
/// @return `nil` only when `error != nil`.
- (nullable ObsResponse *)uploadFileRequest:(ObsRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ObsClientAPISetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ObsClientAPI> *_Nullable api);

NS_ASSUME_NONNULL_END
